import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import ClientProvider from "@/libs/theme/ClientProvider";

import "./load-public-fonts.css";

export const metadata: Metadata = {
  title: "وقتبان-ادمین",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={` bg-background antialiased`}>
        {/* <SplashScreen /> */}
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
