import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Box } from "@mui/material";
import SplashScreen from "@/libs/shared-components/splash-screen/SplashScreen";
import ClientProvider from "@/libs/theme/ClientProvider";

import "./load-public-fonts.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-background antialiased`}
      >
        {/* <SplashScreen /> */}
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
